#!/usr/bin/env python3
"""Generate ``src/html_entities.rs`` from the running CPython's ``html`` tables.

``htmlium`` reproduces ``html.unescape`` bit-for-bit.  The only data it needs are
the three tables that CPython's pure-Python implementation consults:

* ``html.entities.html5``      -- the 2231 named character references;
* ``html._invalid_charrefs``   -- numeric refs that remap to a specific char;
* ``html._invalid_codepoints`` -- numeric refs that resolve to the empty string.

Generating the Rust tables *from CPython's own dicts* (rather than from the WHATWG
JSON) makes parity true by construction: htmlium can only diverge from the stdlib
if the stdlib's tables change, in which case re-running this script regenerates them.

Run via ``make regen-html`` equivalent::

    python tools/generate_html_entities.py            # writes src/html_entities.rs
    python tools/generate_html_entities.py --check     # fail if out of date (CI)

The emitted ``ENTITIES`` array is sorted by key so the Rust side can ``binary_search``
it; keys are ASCII, so Python's code-point sort matches Rust's byte-wise ``str`` Ord.
"""

from __future__ import annotations

import argparse
import sys
from html import _invalid_charrefs, _invalid_codepoints
from html.entities import html5
from pathlib import Path

_OUT = Path(__file__).resolve().parent.parent / "src" / "html_entities.rs"

_HEADER = """\
// @generated by tools/generate_html_entities.py -- DO NOT EDIT BY HAND.
//
// Source: CPython's `html.entities.html5`, `html._invalid_charrefs`, and
// `html._invalid_codepoints` (regenerate with `python tools/generate_html_entities.py`).
//
// `ENTITIES` is sorted by key for binary search; all keys are ASCII so the
// ordering matches Rust's byte-wise `str` Ord. Values may contain up to two
// non-ASCII code points and are emitted with `\\u{..}` escapes.
"""


def rust_str(s: str) -> str:
    """Render a Python str as a Rust double-quoted string literal."""
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= o < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\u{{{o:x}}}")
    out.append('"')
    return "".join(out)


def render() -> str:
    lines = [_HEADER, ""]

    lines.append("pub static ENTITIES: &[(&str, &str)] = &[")
    for key in sorted(html5):
        lines.append(f"    ({rust_str(key)}, {rust_str(html5[key])}),")
    lines.append("];")
    lines.append("")

    lines.append("pub static INVALID_CHARREFS: &[(u32, &str)] = &[")
    for num in sorted(_invalid_charrefs):
        lines.append(f"    (0x{num:04x}, {rust_str(_invalid_charrefs[num])}),")
    lines.append("];")
    lines.append("")

    lines.append("pub static INVALID_CODEPOINTS: &[u32] = &[")
    row: list[str] = []
    for num in sorted(_invalid_codepoints):
        row.append(f"0x{num:x}")
        if len(row) == 12:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if src/html_entities.rs is stale"
    )
    args = parser.parse_args(argv)

    content = render()
    if args.check:
        existing = _OUT.read_text() if _OUT.exists() else ""
        if existing != content:
            print(
                f"{_OUT} is out of date; run python tools/generate_html_entities.py",
                file=sys.stderr,
            )
            return 1
        print(f"{_OUT} is up to date ({len(html5)} entities).")
        return 0

    _OUT.write_text(content)
    print(
        f"wrote {_OUT} ({len(html5)} entities, "
        f"{len(_invalid_charrefs)} invalid charrefs, "
        f"{len(_invalid_codepoints)} invalid codepoints)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
